version: '3.5'

services:
  web:
    image: web
    build:
      context: ./ 
      dockerfile: Dockerfile

    volumes:
      - '.:/app'
    ports:
      - 5000:5000
    environment:
      - APP_NAME={{aliascheck.app_name}}
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=0
      - APP_SETTINGS=app.config.ProductionConfig
      - DATABASE_URL=postgresql://postgres:postgres@web-db:5432/users_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@web-db:5432/users_test
      - SECRET_KEY=change_me_in_prod
      - TWITTER_CONSUMER_KEY=twitter_consumer_key_here
      - TWITTER_CONSUMER_SECRET=twitter_consumer_secret_here
    
    depends_on:
      - web-db
  web-db:
    container_name: web-db
    build:
      context: ./app/db
      dockerfile: Dockerfile
    
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS